version: '3'

services:
  reverse_proxy:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
  client:
        build: 
            context: ./clientApp
            dockerfile: Dockerfile
        depends_on: 
          - backend
        ports: 
          - 5000:80
  backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        depends_on: 
          - database
        ports: 
          - 3000:80
  database:
        image: postgres:10.15-alpine
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
          - pgconf:/etc/postgresql
          - pglog:/var/log/postgresql
        environment:
          - POSTGRES_DB=appdb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=admin

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local